# Generated by Django 5.2.8 on 2025-11-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
