# Generated by Django 5.2.8 on 2025-11-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estagiarios', '0002_estagiario_telefone'),
        ('pacientes', '0002_alter_paciente_data_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('estagiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estagiarios.estagiario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
    ]
