# Generated by Django 5.2.8 on 2025-11-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
