# Generated by Django 6.0 on 2026-03-13 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagiarios', '0002_estagiario_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
